import './globals.css';
import { Roboto } from 'next/font/google';
import SideBar from '../components/side-bar/sideBar';
import styles from './layout.module.scss';

const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'],
  style: ['normal'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Julia`s Portfolio 🤘🏿',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={roboto.className} lang='en'>
      <body className={styles.container}>
        <SideBar />
        <div> {children}</div>
      </body>
    </html>
  );
}
